apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: ""
    role: ""
  name: EtcdRules
spec:
  groups:
  - name: etcd-rules
    rules:
    - expr: count(up{job="kubernetes-apiservers"} == 0) > (count(up{job="kubernetes-apiservers"})
        / 2 - 1)
      record: ""
    - expr: etcd_server_has_leader{job="kubernetes-apiservers"} == 0
      record: ""
    - expr: increase(etcd_server_leader_changes_seen_total{job="kubernetes-apiservers"}[1h])
        > 3
      record: ""
    - expr: histogram_quantile(0.99, rate(etcd_http_successful_duration_seconds_bucket[5m]))
        > 0.15
      record: ""
    - expr: increase(etcd_server_proposals_failed_total{job="kubernetes-apiservers"}[1h])
        > 5
      record: ""
    - expr: histogram_quantile(0.99, rate(etcd_disk_wal_fsync_duration_seconds_bucket[5m]))
        > 0.5
      record: ""
    - expr: histogram_quantile(0.99, rate(etcd_disk_backend_commit_duration_seconds_bucket[5m]))
        > 0.25
      record: ""
